export const environment = {
    production: false,
    baseUrl: '',
    apiUrl: 'http://localhost:8089/',
    MasterapiUrl: 'http://localhost:8089/',
    apiUrlReq: 'http://k8s-istiosys-istioing-2a7bae34ec-0fc243e63169dc07.elb.ap-south-1.amazonaws.com/tariff-grant-bff/',
    setRFQApiUrlReq: 'http://k8s-istiosys-istioing-2a7bae34ec-0fc243e63169dc07.elb.ap-south-1.amazonaws.com/tariff-selling-service-bff/secure/v1/', 
    // apiUrlReq: 'http://k8s-istiosys-istioing-2a7bae34ec-0fc243e63169dc07.elb.ap-south-1.amazonaws.com/tariff-grant-bff/',
    apiUrlMaster: 'http://localhost:8089/',
    apiUrlTariffTransaction: 'http://localhost:8089/',
    // apiUrlRateRequest: 'http://localhost:8083/raterequest/',
    // apiUrlRateInvoice: 'http://localhost:8084/invoice/',
    // apiUrlCargodetail: 'http://localhost:8080/cargodetail/',
    // apiUrlTariffTransaction: 'http://localhost:8088/',
    LegalIntityId: sessionStorage.getItem('legalEntityId'),
    Department:'E',
    UserId: 'EDI',
    useHash: false,
};
